baseURL = 'https://bahdah.github.io/'
languageCode = 'en-us'
title = 'My Blog'
paginate = 5
theme = "PaperMod"

buildDrafts = false
buildFuture = false
buildExpired = false

googleAnalytics = "G-T3GB2SRLJX"

[minify]
    disableXML = true
    minifyOutput = true
[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
author = "Theme PaperMod"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
images = [ "papermod-cover.png" ]

  [params.profileMode]
  enabled = false
  title = "PaperMod"
  imageUrl = "#"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"
