baseURL: "https://bahdahshin.com/"
languageCode: "en-us"
title: Bahdah Shin
paginate: 5
theme: PaperMod

googleAnalytics: G-T3GB2SRLJX

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      urL: /tags/
      weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 11
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 5
    - identifier: about_me
      name: About Me
      url: /about_me/
      weight: 6
    - identifier: resume
      name: Resume
      url: BahdahShinSoftwareEngineering.pdf
      weight: 7


outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: Bahdah Shin's Blog
  author: Bahdah Shin
  defaultTheme: auto
  ShowShareButtons: false
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true


  profileMode:
    enabled: true
    title: "Bahdah Shin"
    subtitle: "Welcome to my blog!"
    buttons:
      - name: About Me
        url: "/about_me/"
      - name: Resume
        url: BahdahShinSoftwareEngineering.pdf

  socialIcons:
    - name: github
      url: "https://github.com/bahdah/bahdah.github.io"
    - name: linkedin
      url: "https://www.linkedin.com/in/bahdah/"
    - name: Rss
      url: "index.xml"

  editPost:
    URL: "https://github.com/bahdah/bahdah.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
