baseURL = 'https://bahdah.github.io/'
languageCode = 'en-us'
title = 'My Blog'
paginate = 5
theme = "PaperMod"

buildDrafts = false
buildFuture = false
buildExpired = false

googleAnalytics = "G-T3GB2SRLJX"

[minify]
    disableXML = true
    minifyOutput = true

[params]
    [profileMode]
        enabled = true
        title = "My Blog"
        subtitle = "This is subtitle"
    
    [fuseOpts]
        isCaseSensitive = false
        shouldSort = true
        location = 0
        distance = 1000
        threshold = 0.4
        minMatchCharLength = 0
        keys = ["title", "permalink", "summary", "content"]
    
[outputs]
    home = ["HTML", "RSS", "JSON"]
